version: "3"
services:
        server:
                image: jetbrains/teamcity-server
                ports:
                        - "8111:8111"
                volumes:
                        - teamcity_ci_data:/data/teamcity_server/datadir
                        - teamcity_ci_log:/opt/teamcity/logs
                        - /var/run/docker.sock:/var/run/docker.sock
        teamcity-agent-1:
                build: ./build_agent/
                environment:
                        - SERVER_URL=http://server:8111
                        - AGENT_NAME="docker_test"
                volumes:
                        - teamcity_agent_test_branch:/data/teamcity_agent/conf
                        - /var/run/docker.sock:/var/run/docker.sock
        teamcity-agent-2:
                build: ./build_agent/
                environment:
                        - SERVER_URL=http://server:8111
                        - AGENT_NAME="docker_dev"
                volumes:
                        - teamcity_agent_development_branch:/data/teamcity_agent/conf
                        - /var/run/docker.sock:/var/run/docker.sock

volumes:
        teamcity_ci_data:
                external: true
        teamcity_ci_log:
                external: true
        teamcity_agent_test_branch:
                external: true
        teamcity_agent_development_branch:
                external: true
