---
AWSTemplateFormatVersion: '2010-09-09'
Description: Syncoid replication target

Parameters:
  MYIP:
    Type: String
    Default: 0.0.0.0
    Description: The IP for Security Group Egress/Ingress

  AMI:
    Type: String
    Default: 'ami-09c7422ca816f0bc1'
    Description: The AMI ID for EC2 launch

Resources:
  ZFSInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: t3a.medium
      KeyName: new-zfs
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: "Project"
          Value: "ZFS-Backups"
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Dynamically generated SG for ZFS replication
      SecurityGroupIngress:
        - CidrIp: !Join
            - ''
            - - !Ref MYIP
              - '/32'
          IpProtocol: tcp
          ToPort: 22
          FromPort: 22
      Tags:
        - Key: "Project"
          Value: "ZFS-Backups"

